### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordBDHG/HealthGPT#13]
### Problem

The current application contains the generic onboarding go the CardinalKit template application based on the [CardinalKit Onboarding Module](https://github.com/StanfordBDHG/CardinalKitOnboarding). It would be good to add a disclaimer, a HealthKit permissions screen, and a screen to enter your OpenAI API key in the onboarding flow.

### Solution

Add or modify the screens to
1. Display a disclaimer and give an overview of the application
2. Ask for the OpenAI API Key of the user and store it in using the [CardinalKit Storage Module](https://github.com/StanfordBDHG/CardinalKitStorage) module.
3. Ask the user to provide access to the HealthKit data before they enter the chat interface.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
Completed by #13.
