### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by ghost** [StanfordBDHG/HealthGPT#15]
### Use Case

Hey can you make a health gpt implementation for android user ? Android user cannot use your app that sound really interesting. And we cannot contribuate with your project due of not interagration with android 

### Problem

Not working with android phone

### Solution

implementation for android phone 

### Alternatives considered

We woiuld be really happy if there is any new version for android user

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by rcourtna** [comment]
Android and Fitbit support ❤️

**Comment by vishnuravi** [comment]
HealthGPT has been built upon the [Stanford Spezi](https://github.com/StanfordSpezi) framework, which is currently only available on iOS. However, an Android version of the framework is currently [in development](https://github.com/StanfordSpezi/SpeziKt). When this is released, it will be possible to build HealthGPT-like functionality for Android upon Spezi!
