### ISSUE TITLE
Error Querying OpenAI Api

### ISSUE THREAD

**Issue by youngfolks** [StanfordBDHG/HealthGPT#30]
### Description

I'm receiving the following error in the console after submitting a message:

Error querying OpenAI API: keyNotFound(CodingKeys(stringValue: "id", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"id\", intValue: nil) (\"id\").", underlyingError: nil))

I have tried adding the api key both on the welcome screen in the app as well as in the OpenAI-info in supporting files.

### Reproduction

Download the respository. Run the app. Insert the API key from your OpenAPI account. Submit a message. Check console for error.

### Expected behavior

Message should return, but there is no connection to openAI due to the error.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
Thank you for the bug report. We will investigate this after we have addressed https://github.com/StanfordBDHG/HealthGPT/issues/28 which might resolve your issue.

**Comment by iamazhar** [comment]
Any update on this issue? Not usable because of this at the moment.

**Comment by PSchmiedmayer** [comment]
@iamazhar Thank you for checking back on the issue; you can follow the progress of the PR here: https://github.com/StanfordBDHG/HealthGPT/pull/31
