### ISSUE TITLE
💾 Internal change: Support local LLMs

### ISSUE THREAD

**Issue by manmatteo** [StanfordBDHG/HealthGPT#38]
### Problem

SpeziLLM supports local LLMs. Using a local LLM seems particularly important when dealing with health data.

### Solution

I see two possibilities: either allow for on-device LLMs with SpeziLLM, or allow customization of the OpenAI API URL, so that the app can be used with, for example, a local ollama server.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
Thank you for the great suggestion @manmatteo! This feature is currently in progress in the following PR: https://github.com/StanfordBDHG/HealthGPT/pull/39

**Comment by vishnuravi** [comment]
This issue has been addressed by #39
