### ISSUE TITLE
🐛 Bug report: TestFlight link closed

### ISSUE THREAD

**Issue by ShantanuNair** [StanfordBDHG/HealthGPT#40]
### Description

The TestFlight link isn't working anymore. Are you open to new users? I'm interested.

### Reproduction

N/A

### Expected behavior

Users can try the app using TestFlight

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by zqyr** [comment]
I second that. Can someone please please let more users join the TestFlight program?

**Comment by PSchmiedmayer** [comment]
Hi @zqyr & @ShantanuNair,

Thank you for your interest in HealthGPT. There is currently no active ongoing development on HealthGPT; we would like to extend and support it but don't have any dedicated funding nor people on the project at this point. 

TestFlight links are only active for 30 days without any feature updates. As soon as we merge a new PR that improves the application and is worth a few releases, we can update that. Feel free to compile and run the application locally in the meantime.
