### ISSUE TITLE
Stream GPT Responses

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordBDHG/HealthGPT#8]
### Use Case

It would be great if the UI and logic would support streaming GPT responses to the client UI.

### Problem

The streaming of responses to the client is currently broken and tracked in https://github.com/MacPaw/OpenAI/issues/14

### Solution

Incorporate the feature once https://github.com/MacPaw/OpenAI/issues/14 is closed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
Addressed by PR #26
